name: IE11 CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:           [ windows-latest ]

    steps:
    - uses: actions/checkout@v2

    - name: echo object
      run: |
        $ie = New-Object -ComObject InternetExplorer.Application
        $ie.Navigate("https://takanoriyanagitani.github.io/cpmap/docs/tests/index/s2m.html")
        $ie

    - name: test
      run: |
        $ie = New-Object -ComObject InternetExplorer.Application
        $ie.Navigate("https://takanoriyanagitani.github.io/cpmap/docs/tests/index/s2m.html")
        $cnt = 64
        while(-not $ie.LocationName -eq "OK" -and -not $ie.LocationName -eq "NG" -and $cnt -gt 0){ $cnt--; sleep 1 }
        $ie.LocationName | findstr "^OK$"
